[package]
name = "cotask"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = "0.9.2"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "cotask"
path = "src/bin/cli.rs"
